databases:
  - name: gossip_db
    databaseName: gossip_db
    user: gossip_db
    region: singapore
    plan: free

services:
  - type: web
    name: gossip_api
    region: singapore
    plan: free
    env: ruby
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gossip_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false